/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithms;

import org.junit.Test;
import static org.junit.Assert.*;

public class ArrayShiftTest {
  // This tests array of even length
  // new value should be exactly in the middle of the array
  @Test
  public void testEvenArray() {
    int[] testArray = new int[] { 1, 2, 4, 5 };
    int testInput = 3;
    int[] expectedArray = new int[] { 1, 2, 3, 4, 5 };
    assertArrayEquals(ArrayShift.insertShiftArray(testArray, testInput), expectedArray);
  }

  //This tests array of odd length
  //new value should be on the first most right half of the array
  @Test
  public void testOddArray() {
    int[] testArray = new int[] { 1, 2, 3, 5, 6 };
    int testInput = 4;
    int[] expectedArray = new int[] { 1, 2, 3, 4, 5, 6 };
    assertArrayEquals(ArrayShift.insertShiftArray(testArray, testInput), expectedArray);
  }

  //new value should be the only value in the array
  @Test
  public void testEmptyArray() {
    int[] testArray = new int[] {};
    int testInput = 1;
    int[] expectedArray = new int[] {1};
    assertArrayEquals(ArrayShift.insertShiftArray(testArray, testInput), expectedArray);
  }
}
